const createMenu = () => {
  const element = document.createElement("div");
  const headermenu = document.createElement("div");
  const headerLogo = document.createElement("img");
  const headerTitle = document.createElement("h2");
  const startersContainer = document.createElement("div");
  const mainCourseContainer = document.createElement("div");
  const dessertContainer = document.createElement("div");
  const startersLogo = document.createElement("img");
  const startersTitle = document.createElement("h3");
  const mainCourseLogo = document.createElement("img");
  const mainCourseTitle = document.createElement("h3");
  const dessertLogo = document.createElement("img");
  const dessertTitle = document.createElement("h3");
  const boxes = document.createElement("div");
  const starterOne = document.createElement("p");
  const starterTwo = document.createElement("p");
  const starterThree = document.createElement("p");
  const starterFour = document.createElement("p");
  const mainOne = document.createElement("p");
  const mainTwo = document.createElement("p");
  const mainThree = document.createElement("p");
  const mainFour = document.createElement("p");
  const dessertOne = document.createElement("p");
  const dessertTwo = document.createElement("p");
  const dessertThree = document.createElement("p");
  const dessertFour = document.createElement("p");
  boxes.classList.add("boxes");
  startersLogo.classList.add("salad-logo");
  mainCourseLogo.classList.add("meal-logo");
  dessertLogo.classList.add("cake-logo");
  startersLogo.src = "./img/salad.svg";
  startersLogo.alt = "A salad logo";
  startersTitle.innerText = "STARTERS";
  mainCourseLogo.src = "./img/meal.svg";
  mainCourseLogo.alt = "A meal logo";
  mainCourseTitle.innerText = "MAIN COURSE";
  dessertLogo.src = "./img/cake-logo.svg";
  dessertLogo.alt = "A cake logo";
  dessertTitle.innerText = "DESSERT";
  headerLogo.src = "./img/chef-icon.svg";
  headerLogo.alt = "A chief logo";
  headerLogo.classList.add("chef-logo");
  headermenu.classList.add("header-menu");
  headerTitle.classList.add("header-title");
  startersContainer.classList.add("starters-container");
  mainCourseContainer.classList.add("maincourse-container");
  dessertContainer.classList.add("dessert-container");
  headerTitle.innerText = "OUR MENU";
  element.classList.add("menu-container");
  headermenu.appendChild(headerLogo);
  headermenu.appendChild(headerTitle);
  element.appendChild(headermenu);
  element.appendChild(boxes);
  boxes.appendChild(startersContainer);
  boxes.appendChild(mainCourseContainer);
  boxes.appendChild(dessertContainer);
  startersContainer.appendChild(startersLogo);
  starterOne.classList.add("starter-one");
  starterTwo.classList.add("starter-two");
  starterThree.classList.add("starter-three");
  starterFour.classList.add("starter-four");
  mainOne.classList.add("main-one");
  mainTwo.classList.add("main-two");
  mainThree.classList.add("main-three");
  mainFour.classList.add("main-four");
  dessertOne.classList.add("dessert-one");
  dessertTwo.classList.add("dessert-two");
  dessertThree.classList.add("dessert-three");
  dessertFour.classList.add("dessert-four");
  starterOne.innerHTML = "Mediterranean salad";
  starterTwo.innerHTML = "Andalusian gazpacho";
  starterThree.innerHTML = "Ham and cheese saint jacobs";
  starterFour.innerHTML = "Castilian soup";
  mainOne.innerHTML = "Beef ragout";
  mainTwo.innerHTML = "Baked macaroni with sirloin";
  mainThree.innerHTML = "Lamb chops";
  mainFour.innerHTML = "Fried turbot with potatoes";
  dessertOne.textContent = 'Homemade cheese and blueberry pie';
  dessertTwo.textContent = 'Chocolate and pistachio macadamia nut ice cream';
  dessertThree.textContent = 'Catalan cream';
  dessertFour.innerText = 'Fresh fruit';
  startersContainer.appendChild(startersTitle);
  startersContainer.appendChild(starterOne);
  startersContainer.appendChild(starterTwo);
  startersContainer.appendChild(starterThree);
  startersContainer.appendChild(starterFour);
  mainCourseContainer.appendChild(mainCourseLogo);
  mainCourseContainer.appendChild(mainCourseTitle);
  mainCourseContainer.appendChild(mainOne);
  mainCourseContainer.appendChild(mainTwo);
  mainCourseContainer.appendChild(mainThree);
  mainCourseContainer.appendChild(mainFour);
  dessertContainer.appendChild(dessertLogo);
  dessertContainer.appendChild(dessertTitle);
  dessertContainer.appendChild(dessertOne);
  dessertContainer.appendChild(dessertTwo);
  dessertContainer.appendChild(dessertThree);
  dessertContainer.appendChild(dessertFour);
  return element;
};

export default createMenu;
